apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-central-config
  namespace: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'self'
        static_configs:
          - targets: ['localhost:9090']

