# prom-agent-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-agent-wal
  namespace: prometheus
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
