apiVersion: v1
kind: ConfigMap
metadata:
  name: elastalert-config # 이전과 동일한 이름 사용
data:
  # 1. 메인 설정 파일 (config.yaml) 내용 업데이트
  config.yaml: |
    rules_folder: /opt/elastalert/rules
    run_every:
      seconds: 10
    buffer_time:
      minutes: 10
    es_host: es-cluster-es-http  # K8s 서비스 이름 사용 (localhost 아님!)
    es_port: 9200
    use_ssl: true
    verify_certs: false
    es_username: elastic
    es_password: "${ES_PASSWORD}"
    writeback_index: elastalert_status
    alert_time_limit:
      days: 2

  # 2. 새로운 규칙 파일 (service_error_rule.yaml) 추가
  service_error_rule.yaml: |
    name: Service-Error-Alert
    type: any
    index: service-logs* # 인덱스 패턴에 와일드카드 추가
    filter:
      - term:
          is_error: true
    query_key:
      - sourceIP
      - result
    realert:
      minutes: 10
    alert:
      - post
    http_post_url: https://8gw8cnfky5.execute-api.ap-northeast-2.amazonaws.com/servicealert
    http_post_headers:
      Content-Type: "application/json"
