apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-central
  namespace: prometheus
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-central
  namespace: prometheus
spec:
  serviceName: prometheus-central
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-central
  template:
    metadata:
      labels:
        app: prometheus-central
    spec:
      serviceAccountName: prometheus-central
      containers:
        - name: prometheus
          image: prom/prometheus:v2.52.0
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --storage.tsdb.retention.time=7d
            - --web.enable-remote-write-receiver   # Agent가 전송할 데이터 수신
          ports:
            - name: http
              containerPort: 9090
          volumeMounts:
            - name: data
              mountPath: /prometheus
            - name: config
              mountPath: /etc/prometheus
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: prometheus-central-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: local-path
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-central-lb
  namespace: prometheus
  labels:
    app: prometheus-central
spec:
  type: LoadBalancer
  selector:
    app: prometheus-central
  ports:
    - name: http
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-prometheus-central-0
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeName: prometheus-pv   

