apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: prometheus
  labels: { app: grafana }
spec:
  replicas: 1
  selector:
    matchLabels: { app: grafana }
  template:
    metadata:
      labels: { app: grafana }
    spec:
      serviceAccountName: grafana
      containers:
        - name: grafana
          image: grafana/grafana:10.4.5
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: asdf
          readinessProbe:
            httpGet: { path: /login, port: 3000 }
            initialDelaySeconds: 10
            periodSeconds: 10
---

apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: prometheus
  labels: { app: grafana }
spec:
  type: NodePort
  selector: { app: grafana }
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 32000   # 30000~32767 범위에서 고르면 됨

