apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  namespace: metallb-system
  name: lmv-pool
spec:
  addresses:
    - 192.168.1.230-192.168.1.240
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  namespace: metallb-system
  name: lmv-advertisement
spec:
  ipAddressPools:
    - lmv-pool

