apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: prometheus
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels: # 어떤 Pod들을 이 DaemonSet이 관리할지 결정. Pod의 label과 일치해야 함
      app: node-exporter
  template:
    metadata:
      labels: # Pod에 붙는 라벨 정의. selector와 일치해야 함
        app: node-exporter
    spec:
      serviceAccountName: node-exporter
      hostNetwork: true
      hostPID: true
      containers:
      - name: node-exporter
        image: quay.io/prometheus/node-exporter:v1.8.1
        args: # Node Exporter에 전달하는 실행 인자
          - --path.rootfs=/ # 기본값으로, 루트 파일 시스템을 그대로 사용
        ports:
        - name: metrics
          containerPort: 9100
          hostPort: 9100 # hostPort를 열면, Prometheus가 http://<노드 IP>:9100/metrics로 바로 접근 가능해진다.
        resources:
          requests: # 최소 보장 리소스
            cpu: 50m
            memory: 64Mi
          limits: # 최대 보장 리소스
            cpu: 200m
            memory: 200Mi

